<?php
/** Published ingredient findings, researched 2026-10-08. Not customer reviews. */
defined( 'ABSPATH' ) || exit;

return [
	'compound-semaglutide' => [
		'name' => 'Semaglutide',
		'context' => 'STEP 1 · 1,961 adults with overweight or obesity, without diabetes · 68 weeks',
		'note' => 'Study participants received semaglutide 2.4 mg weekly plus lifestyle support. These are trial findings, not results established for this compounded formulation. Nausea and diarrhea were common.',
		'cards' => [
			[
				'tag' => 'Human trial',
				'title' => '14.9% average weight loss',
				'text' => 'Compared with 2.4% on placebo at week 68.',
				'source' => 'Wilding et al. · 2021',
				'url' => 'https://pubmed.ncbi.nlm.nih.gov/33567185/',
			],
			[
				'tag' => 'Human trial',
				'title' => '86.4% lost at least 5%',
				'text' => 'Compared with 31.5% on placebo at week 68.',
				'source' => 'Wilding et al. · 2021',
				'url' => 'https://pubmed.ncbi.nlm.nih.gov/33567185/',
			],
			[
				'tag' => 'Human trial',
				'title' => '69.1% lost at least 10%',
				'text' => 'Compared with 12.0% on placebo at week 68.',
				'source' => 'Wilding et al. · 2021',
				'url' => 'https://pubmed.ncbi.nlm.nih.gov/33567185/',
			],
		],
	],
	'compound-tirzepatide' => [
		'name' => 'Tirzepatide',
		'context' => 'SURMOUNT-1 · 2,539 adults with obesity or overweight and a complication, without diabetes · 72 weeks',
		'note' => 'Figures shown here are from the 15 mg weekly trial group with lifestyle intervention, not this compounded formulation. Gastrointestinal side effects were common; study dosing is not a personal dosing recommendation.',
		'cards' => [
			[
				'tag' => 'Human trial',
				'title' => '20.9% average weight loss',
				'text' => 'Compared with 3.1% on placebo at week 72.',
				'source' => 'Jastreboff et al. · 2022',
				'url' => 'https://pubmed.ncbi.nlm.nih.gov/35658024/',
			],
			[
				'tag' => 'Human trial',
				'title' => '91% lost at least 5%',
				'text' => 'Compared with 35% on placebo at week 72.',
				'source' => 'Jastreboff et al. · 2022',
				'url' => 'https://pubmed.ncbi.nlm.nih.gov/35658024/',
			],
			[
				'tag' => 'Human trial',
				'title' => '57% lost at least 20%',
				'text' => 'Compared with 3% on placebo at week 72.',
				'source' => 'Jastreboff et al. · 2022',
				'url' => 'https://pubmed.ncbi.nlm.nih.gov/35658024/',
			],
		],
	],
	'testosterone' => [
		'name' => 'Testosterone',
		'context' => 'Testosterone Trials · Symptomatic men age 65+ with low testosterone · One year',
		'note' => 'These trials used testosterone gel, not testosterone cypionate injections. Findings cannot establish the same outcomes for this formulation or for people without diagnosed testosterone deficiency.',
		'cards' => [
			[
				'tag' => 'Human trial',
				'title' => 'Improved sexual function',
				'text' => 'Testosterone treatment produced a moderate improvement compared with placebo.',
				'source' => 'Snyder et al. · 2016',
				'url' => 'https://pubmed.ncbi.nlm.nih.gov/26886521/',
			],
			[
				'tag' => 'Human trial',
				'title' => 'Some mood improvement',
				'text' => 'Researchers reported modest benefits in mood and depressive symptoms.',
				'source' => 'Snyder et al. · 2016',
				'url' => 'https://pubmed.ncbi.nlm.nih.gov/26886521/',
			],
			[
				'tag' => 'Evidence limit',
				'title' => 'No proven vitality benefit',
				'text' => 'The trial did not meet its primary vitality outcome. More energy is not a guaranteed result.',
				'source' => 'Snyder et al. · 2016',
				'url' => 'https://pubmed.ncbi.nlm.nih.gov/26886521/',
			],
		],
	],
	'hcg' => [
		'name' => 'HCG',
		'context' => 'Hormone research and prescribing information',
		'note' => 'HCG findings depend on the diagnosis and treatment regimen. A short-term hormone response does not establish improved fertility or a personal treatment outcome.',
		'cards' => [
			[
				'tag' => 'Human trial',
				'title' => 'Testicular testosterone maintained',
				'text' => 'In a three-week study of 29 men receiving testosterone enanthate, added HCG maintained intratesticular testosterone at selected doses.',
				'source' => 'Coviello et al. · 2005',
				'url' => 'https://pubmed.ncbi.nlm.nih.gov/15713727/',
			],
			[
				'tag' => 'Prescribing information',
				'title' => 'Specific hormone-deficiency use',
				'text' => 'The PREGNYL label includes selected cases of male hypogonadotropic hypogonadism. This is a specific diagnosis, not general wellness.',
				'source' => 'PREGNYL prescribing information',
				'url' => 'https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=1e94155f-19be-4944-b197-be4edbb4faf9',
			],
			[
				'tag' => 'Evidence limit',
				'title' => 'Fertility remains a separate question',
				'text' => 'The three-week study measured hormone levels; it did not demonstrate pregnancies or long-term preservation of sperm production.',
				'source' => 'Coviello et al. · 2005',
				'url' => 'https://pubmed.ncbi.nlm.nih.gov/15713727/',
			],
		],
	],
	'compound-sildenafil' => [
		'name' => 'Sildenafil',
		'label_url' => 'https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=edb0919d-cbf1-4968-b0eb-342aa811c2ce',
		'context' => 'Randomized trials in men with erectile dysfunction · Oral sildenafil',
		'note' => 'These findings concern studied oral sildenafil regimens, not guaranteed outcomes for this product. Headache, flushing and indigestion were common adverse effects. Sildenafil must not be combined with nitrates.',
		'cards' => [
			[
				'tag' => 'Human trial',
				'title' => '69% successful attempts',
				'text' => 'Versus 22% with placebo during the final four weeks of a 12-week flexible-dose trial. This measures attempts, not people.',
				'source' => 'Goldstein et al. · 1998',
				'url' => 'https://pubmed.ncbi.nlm.nih.gov/9580646/',
			],
			[
				'tag' => 'Human trial',
				'title' => '5.9 successes per month',
				'text' => 'The average number of successful intercourse attempts was 5.9 with sildenafil versus 1.5 with placebo.',
				'source' => 'Goldstein et al. · 1998',
				'url' => 'https://pubmed.ncbi.nlm.nih.gov/9580646/',
			],
			[
				'tag' => 'Human trial',
				'title' => 'Improved erection scores',
				'text' => 'In the 100 mg study group, the average erection-achievement score increased from 2.0 to 4.0 out of 5.',
				'source' => 'Goldstein et al. · 1998',
				'url' => 'https://pubmed.ncbi.nlm.nih.gov/9580646/',
			],
		],
	],
	'compound-oral-tadalafil' => [
		'name' => 'Tadalafil',
		'label_url' => 'https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=78509a43-a907-4359-9022-f38c4f765880',
		'context' => 'Randomized trial · 348 men with erectile dysfunction · Oral tadalafil 20 mg',
		'note' => 'Results describe the studied oral formulation, not a guarantee for this product. Headache, flushing, indigestion and muscle pain were more frequent than with placebo. Tadalafil must not be combined with nitrates.',
		'cards' => [
			[
				'tag' => 'Human trial',
				'title' => '52.9% success at 24 hours',
				'text' => 'Versus 29.1% with placebo. Figures describe successful intercourse attempts, not the percentage of patients cured.',
				'source' => 'Porst et al. · 2003',
				'url' => 'https://pubmed.ncbi.nlm.nih.gov/12837435/',
			],
			[
				'tag' => 'Human trial',
				'title' => '59.2% success at 36 hours',
				'text' => 'Versus 28.3% with placebo, showing a longer opportunity to respond to sexual stimulation.',
				'source' => 'Porst et al. · 2003',
				'url' => 'https://pubmed.ncbi.nlm.nih.gov/12837435/',
			],
			[
				'tag' => 'Study interpretation',
				'title' => 'Up to 36-hour responsiveness',
				'text' => 'The study assessed response at 24 and 36 hours. This does not mean a continuous erection or guaranteed effectiveness.',
				'source' => 'Porst et al. · 2003',
				'url' => 'https://pubmed.ncbi.nlm.nih.gov/12837435/',
			],
		],
	],
	'bpc' => [
		'name' => 'BPC-157',
		'context' => 'Small retrospective report · Direct knee-joint injections',
		'note' => 'This uncontrolled report cannot prove efficacy or predict results from other injection routes, doses or formulations. It did not establish cartilage repair or long-term safety.',
		'cards' => [
			[
				'tag' => 'Small human report',
				'title' => '11 of 12 reported relief',
				'text' => 'Eleven of twelve BPC-157-only recipients reported less knee pain after joint injection.',
				'source' => 'Lee & Padgett · 2021',
				'url' => 'https://pubmed.ncbi.nlm.nih.gov/34324435/',
			],
			[
				'tag' => 'Evidence limit',
				'title' => 'No placebo comparison',
				'text' => 'Without a control group, the cause of the reported improvement remains uncertain.',
				'source' => 'Lee & Padgett · 2021',
				'url' => 'https://pubmed.ncbi.nlm.nih.gov/34324435/',
			],
			[
				'tag' => 'Safety evidence',
				'title' => 'Safety information is limited',
				'text' => 'FDA identifies limited safety data and potential immune-reaction and impurity concerns for compounded BPC-157.',
				'source' => 'FDA · Compounding safety',
				'url' => 'https://www.fda.gov/drugs/human-drug-compounding/certain-bulk-drug-substances-use-compounding-may-present-significant-safety-risks',
			],
		],
	],
	'motsc' => [
		'name' => 'MOTS-c',
		'context' => 'Exercise and metabolic research · Animal experiments and human observations',
		'note' => 'The treatment findings shown here are in mice. Observing naturally occurring MOTS-c in people does not show that MOTS-c injections improve human fitness or longevity.',
		'cards' => [
			[
				'tag' => 'Animal study',
				'title' => 'Better performance in mice',
				'text' => 'MOTS-c treatment improved physical performance in young, middle-aged and older mice.',
				'source' => 'Reynolds et al. · 2021',
				'url' => 'https://www.nature.com/articles/s41467-020-20790-0',
			],
			[
				'tag' => 'Human observation',
				'title' => 'Natural levels rose with exercise',
				'text' => 'Exercise increased the body’s own MOTS-c in muscle and circulation. Participants were not treated with MOTS-c injections.',
				'source' => 'Reynolds et al. · 2021',
				'url' => 'https://www.nature.com/articles/s41467-020-20790-0',
			],
			[
				'tag' => 'Evidence limit',
				'title' => 'Human injection benefits unestablished',
				'text' => 'FDA reports no identified human exposure data for administered MOTS-c in its cited safety assessment.',
				'source' => 'FDA · Compounding safety',
				'url' => 'https://www.fda.gov/drugs/human-drug-compounding/certain-bulk-drug-substances-use-compounding-may-present-significant-safety-risks',
			],
		],
	],
	'epithalon' => [
		'name' => 'Epithalon',
		'context' => 'Epitalon laboratory research · Human cell lines',
		'note' => 'Cell-culture findings do not establish longer life, better sleep or improved health in people receiving Epithalon injections.',
		'cards' => [
			[
				'tag' => 'Cell study',
				'title' => 'Longer telomeres in cells',
				'text' => 'A 2025 laboratory study found telomere lengthening in normal epithelial and fibroblast cells exposed to epitalon.',
				'source' => 'Al-Dulaimi et al. · 2025',
				'url' => 'https://pubmed.ncbi.nlm.nih.gov/40908429/',
			],
			[
				'tag' => 'Cell study',
				'title' => 'Telomerase activity increased',
				'text' => 'Researchers observed changes in telomerase-related activity in normal cells. This is a laboratory marker, not a clinical anti-aging result.',
				'source' => 'Al-Dulaimi et al. · 2025',
				'url' => 'https://pubmed.ncbi.nlm.nih.gov/40908429/',
			],
			[
				'tag' => 'Safety evidence',
				'title' => 'Human safety remains uncertain',
				'text' => 'FDA identifies missing route-specific safety information and potential immune-reaction concerns for compounded epitalon.',
				'source' => 'FDA · Compounding safety',
				'url' => 'https://www.fda.gov/drugs/human-drug-compounding/certain-bulk-drug-substances-use-compounding-may-present-significant-safety-risks',
			],
		],
	],
	'compound-injectable-nad' => [
		'name' => 'NAD+',
		'context' => 'Pilot research · Six-hour intravenous infusion',
		'note' => 'This pilot measured NAD+ processing in blood and urine. It did not establish improvements in fatigue, cognition or longevity, or equivalent effects from other injection routes.',
		'cards' => [
			[
				'tag' => 'Human pilot',
				'title' => 'Blood metabolites changed',
				'text' => 'A small infusion study documented changes in circulating NAD+ metabolites during and after intravenous treatment.',
				'source' => 'Grant et al. · 2019',
				'url' => 'https://pmc.ncbi.nlm.nih.gov/articles/PMC6751327/',
			],
			[
				'tag' => 'Human pilot',
				'title' => 'Urinary excretion increased',
				'text' => 'NAD+ and methylnicotinamide excretion increased at six hours, helping characterize how the infused substance was processed.',
				'source' => 'Grant et al. · 2019',
				'url' => 'https://pmc.ncbi.nlm.nih.gov/articles/PMC6751327/',
			],
			[
				'tag' => 'Evidence limit',
				'title' => 'Wellness benefits not measured',
				'text' => 'The pilot studied metabolism rather than energy, memory or lifespan. Biomarker changes alone do not prove a felt benefit.',
				'source' => 'Grant et al. · 2019',
				'url' => 'https://pmc.ncbi.nlm.nih.gov/articles/PMC6751327/',
			],
		],
	],
	'compound-injectable-sermorelin' => [
		'name' => 'Sermorelin',
		'context' => 'GHRH(1–29) study · 11 older men · Six weeks',
		'note' => 'This small study evaluated nightly GHRH(1–29), the peptide used in sermorelin. Its limited size and duration do not establish broad anti-aging or body-composition benefits.',
		'cards' => [
			[
				'tag' => 'Small human study',
				'title' => 'Nighttime growth hormone increased',
				'text' => 'Average nocturnal growth hormone release and peak amplitude increased after six weeks. IGF-I did not increase.',
				'source' => 'Vittone et al. · 1997',
				'url' => 'https://pubmed.ncbi.nlm.nih.gov/9005976/',
			],
			[
				'tag' => 'Small human study',
				'title' => 'Some strength measures improved',
				'text' => 'Two of six strength measures and one abdominal-endurance measure improved. The findings were not uniform across all tests.',
				'source' => 'Vittone et al. · 1997',
				'url' => 'https://pubmed.ncbi.nlm.nih.gov/9005976/',
			],
			[
				'tag' => 'Evidence limit',
				'title' => 'No body-composition change',
				'text' => 'Researchers found no change in weight or measured muscle and fat during the six-week study.',
				'source' => 'Vittone et al. · 1997',
				'url' => 'https://pubmed.ncbi.nlm.nih.gov/9005976/',
			],
		],
	],
	'compound-injectable-glutathione' => [
		'name' => 'Glutathione',
		'context' => 'Randomized pilot · 21 people with Parkinson’s disease · Four weeks',
		'note' => 'This disease-specific IV study does not establish benefits for general wellness, skin brightening or other injection routes. Findings should not be interpreted as a Parkinson’s treatment recommendation.',
		'cards' => [
			[
				'tag' => 'Human pilot',
				'title' => 'Short-term tolerability observed',
				'text' => 'Reported adverse events were similar with IV glutathione and placebo; no participants withdrew because of adverse events.',
				'source' => 'Hauser et al. · 2009',
				'url' => 'https://pubmed.ncbi.nlm.nih.gov/19230029/',
			],
			[
				'tag' => 'Evidence limit',
				'title' => 'No significant symptom difference',
				'text' => 'Changes in Parkinson’s disease rating scores were not statistically different between the glutathione and placebo groups.',
				'source' => 'Hauser et al. · 2009',
				'url' => 'https://pubmed.ncbi.nlm.nih.gov/19230029/',
			],
			[
				'tag' => 'Evidence limit',
				'title' => 'Larger studies needed',
				'text' => 'With only 21 randomized participants, the study could not establish a reliable clinical benefit or long-term safety.',
				'source' => 'Hauser et al. · 2009',
				'url' => 'https://pubmed.ncbi.nlm.nih.gov/19230029/',
			],
		],
	],
	'tesamorelin-ipamorelin' => [
		'name' => 'Tesamorelin / Ipamorelin',
		'context' => 'Ingredient research · These studies did not test the combined blend',
		'note' => 'Tesamorelin findings were in people with HIV-associated abdominal fat accumulation. Neither cited study establishes the results, dosing or safety of this tesamorelin/ipamorelin blend.',
		'cards' => [
			[
				'tag' => 'Tesamorelin trial',
				'title' => '10.9% less visceral fat',
				'text' => 'At six months, visceral fat decreased 10.9% with tesamorelin alone versus 0.6% with placebo in a 404-patient trial.',
				'source' => 'Falutz et al. · 2010',
				'url' => 'https://pubmed.ncbi.nlm.nih.gov/20101189/',
			],
			[
				'tag' => 'Ipamorelin study',
				'title' => 'Growth hormone release observed',
				'text' => 'An IV ipamorelin study in healthy men measured a temporary rise in growth hormone. It did not test fat loss.',
				'source' => 'Gobburu et al. · 1999',
				'url' => 'https://pubmed.ncbi.nlm.nih.gov/10496658/',
			],
			[
				'tag' => 'Evidence limit',
				'title' => 'Blend outcomes not established',
				'text' => 'Separate ingredient findings cannot demonstrate that adding ipamorelin improves tesamorelin’s effects. The cited tesamorelin trial did not include ipamorelin.',
				'source' => 'Falutz et al. · 2010',
				'url' => 'https://pubmed.ncbi.nlm.nih.gov/20101189/',
			],
		],
	],
	'cjc1295-ipamorelin' => [
		'name' => 'CJC-1295 / Ipamorelin',
		'context' => 'Ingredient research · Hormone measurements in healthy adults',
		'note' => 'The CJC study used a long-acting formulation; the ipamorelin study used IV administration. Neither tested this combined product or established improved recovery, sleep or body composition.',
		'cards' => [
			[
				'tag' => 'CJC-1295 study',
				'title' => 'Growth hormone levels increased',
				'text' => 'Long-acting CJC-1295 alone increased mean growth hormone concentrations 2–10 fold after a single injection in healthy adults.',
				'source' => 'Teichman et al. · 2006',
				'url' => 'https://pubmed.ncbi.nlm.nih.gov/16352683/',
			],
			[
				'tag' => 'Ipamorelin study',
				'title' => 'A temporary hormone pulse',
				'text' => 'IV ipamorelin produced one episode of growth hormone release, with a peak at about 40 minutes.',
				'source' => 'Gobburu et al. · 1999',
				'url' => 'https://pubmed.ncbi.nlm.nih.gov/10496658/',
			],
			[
				'tag' => 'Safety evidence',
				'title' => 'Clinical safety data are limited',
				'text' => 'FDA notes limited clinical data for CJC-1295 and reports of increased heart rate and systemic vasodilation.',
				'source' => 'FDA · Compounding safety',
				'url' => 'https://www.fda.gov/drugs/human-drug-compounding/certain-bulk-drug-substances-use-compounding-may-present-significant-safety-risks',
			],
		],
	],
	'2606' => [
		'name' => 'Wolverine · BPC-157 / TB-500',
		'context' => 'Ingredient research · A small knee-injection report',
		'note' => 'The report studied BPC-157 with TB4, not a verified match to this BPC-157/TB-500 formulation. Direct joint-injection findings cannot establish results for this blend or another route.',
		'cards' => [
			[
				'tag' => 'Small human report',
				'title' => 'Three of four reported relief',
				'text' => 'Three of four BPC-157/TB4 recipients reported less knee pain; no placebo comparison.',
				'source' => 'Lee & Padgett · 2021',
				'url' => 'https://pubmed.ncbi.nlm.nih.gov/34324435/',
			],
			[
				'tag' => 'Evidence limit',
				'title' => 'Combination benefit remains uncertain',
				'text' => 'Four combination recipients cannot establish superiority over BPC-157 alone.',
				'source' => 'Lee & Padgett · 2021',
				'url' => 'https://pubmed.ncbi.nlm.nih.gov/34324435/',
			],
			[
				'tag' => 'Evidence limit',
				'title' => 'Tissue repair was not confirmed',
				'text' => 'Follow-up imaging was recommended; reported pain relief does not prove structural repair.',
				'source' => 'Lee & Padgett · 2021',
				'url' => 'https://pubmed.ncbi.nlm.nih.gov/34324435/',
			],
		],
	],
	'klow-stack-bpc157-10mg-ghk-cu-50mg-tb50010mg-kpv-10mg' => [
		'name' => 'KLOW · Four-peptide blend',
		'context' => 'Ingredient research · Animal models and a small human report',
		'note' => 'These separate studies did not test KLOW’s four-ingredient blend. Their findings do not establish the blend’s benefits, interactions or safety in people.',
		'cards' => [
			[
				'tag' => 'BPC-157 · Human report',
				'title' => 'Early knee-pain findings',
				'text' => 'An uncontrolled report found knee-pain relief in 11 of 12 BPC-157-only recipients.',
				'source' => 'Lee & Padgett · 2021',
				'url' => 'https://pubmed.ncbi.nlm.nih.gov/34324435/',
			],
			[
				'tag' => 'GHK-Cu · Animal study',
				'title' => 'More collagen in rat wounds',
				'text' => 'GHK-Cu increased collagen accumulation in implanted wound chambers in rats. Human injection outcomes were not studied.',
				'source' => 'Maquart et al. · 1993',
				'url' => 'https://pubmed.ncbi.nlm.nih.gov/8227353/',
			],
			[
				'tag' => 'KPV · Animal study',
				'title' => 'Reduced inflammation in mice',
				'text' => 'An oral nanoparticle formulation containing KPV improved experimental colitis in mice. This was not an injectable blend.',
				'source' => 'Xiao et al. · 2017',
				'url' => 'https://pubmed.ncbi.nlm.nih.gov/28143741/',
			],
		],
	],
];
